---
title: "Transcriptional and Translational Dynamics of Zika and Dengue Virus Infection"
author: "Dylan Harris"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(tidyverse)

```{r}
#Load data and packages
library(tidyverse)
library(data.table)
Ribodiff.ZIKV <- fread("GSE207347_A1B1_vs_A2B2_ZIKV_ribodiff_name.txt.gz")
Ribodff.DENV <- fread("GSE207347_A1B1_vs_A3B3_DENV_ribodiff_name.txt.gz")
DESeq2.ZIKV <- fread("GSE207347_ZIKV_DESeq2_result_name.txt.gz")
DESeq2.DENV <- fread("GSE207347_DENV_DESeq2_result_name.txt.gz")
```

```{r}
#Grabbing tRNA Synthetases
ZIKV.trna <- subset(DESeq2.ZIKV, na %in% c("CARS", "YARS", "WARS", "AARS", "MARS", "SARS", "GARS", "VARS", "TARS", "IARS"))
DENV.trna <- subset(DESeq2.DENV, na %in% c("CARS", "YARS", "WARS", "AARS", "MARS", "SARS", "GARS", "VARS", "TARS", "IARS"))

#Combining ZIKV and DENV data
ZIKV.trna$virus <- "ZIKV"
DENV.trna$virus <- "DENV"
complete.trna <- rbind(ZIKV.trna, DENV.trna)

ggplot(complete.trna, aes(x=na, y=log2FoldChange, label=log2FoldChange)) +
  geom_bar(stat = "identity", aes(fill=virus), width=0.75, show.legend = FALSE) +
  ggtitle("Aminoacyl tRNA Sythetases") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,), 
        plot.title = element_text(hjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")) +
  xlab("Gene Name") + ylab("RNA log2 Fold Change") +
  facet_wrap(~virus)
#So weirdly, the paper shows TARS decreasing for DENV, but examining the data shows otherwise? Maybe they used a different variant of TARS i.e. TARSL2?
#Also can't seem to adjust color of the bars.
```


```{r}
subset(Ribodiff.ZIKV, padj < 0.05)
fig3a <- ggplot(subset(Ribodiff.ZIKV, !is.nan(padj)),
                aes(x = `log2FC_TE(DrugTreated vs Control)`, y = padj))
fig3a +
  geom_point(aes(color = padj > 0.05), show.legend = FALSE) +
  xlim(-8, 8) + ylim(0.001, 1) + xlab("log2FC_TE(DrugTreated vs Control)") +
  ylab("q value (log10)") + scale_y_log10() + #Can't scale y-value in 2 different ways, If I put in scale_y_reverse() it will overwrite the log10 command
  scale_color_manual(values = c('red', 'black')) +
  geom_hline(yintercept=0.05, linetype=2, col="black") +
  geom_vline(xintercept=0, linetype=2, col="black") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"))
#They also seem to remove a chunk of data. Maybe this has to do with adjustments to their fdr? Or they just cut out a chunk of the data that didn't mean much.
```

```{r}
DESeq2.ZIKV$fdr <- p.adjust(DESeq2.ZIKV$pvalue, method='fdr')
subset(DESeq2.ZIKV, fdr < 0.05)
subset(DESeq2.ZIKV, padj < 0.05)
DESeq2.DENV$fdr <- p.adjust(DESeq2.DENV$pvalue, method='fdr')
subset(DESeq2.DENV, fdr < 0.05)
subset(DESeq2.DENV, padj < 0.05)
```
There seems to be some kind of algorithmic difference between the padj from the
data and the fdr p.adjust that R does.
